### ISSUE TITLE
phone number

### ISSUE THREAD

**Issue by Jbuehler22** [jacbart/Bartlett_CSCI2270_FinalProject#17]
I was testing if your phone number print problem was a white space issu, but you you don't put spaces in the phone number when entering the number your program crashes. It throws a std::out_of_range instance and terminates.

**Comment by Jbuehler22** [comment]
"but if you"

**Comment by jacbart** [comment]
I forgot to specify, but yes you have to type it with no spaces.

**Comment by jacbart** [comment]
Never got a chance to improve that

**Comment by Jbuehler22** [comment]
well the program crashes if you don't have spaces

**Comment by peterdelevoryas** [comment]
The issue isn't related to spaces, the spaces simply prevent `stoi` from capturing the entire string (`stoi` will only convert the first part of the parameter string which is a continuous number, then it discards the rest). The issue is that `int` was used to hold the phone number of the contact, and `int`'s maximum size is much smaller than 10^9 (a 10 digit phone number), in fact an integer's required max is on the order of 5 times too small for the minimum value of a 10 digit phone number. In order to hold 9,999,999,999 (max possible value of 10 digit phone number), it is necessary to use an unsigned long to hold the phone number, and use `stoul` rather that `stoi`. I'm going to submit a pull request which contains the code to fix this issue, please merge it with your repository!
